### ISSUE TITLE
Template Compiler error in Ember 3.25

### ISSUE THREAD

**Issue by nwhittaker** [lifeart/ember-ast-hot-load#558]
After upgrading a project to Ember 3.25, the following error appears when running `ember serve`:

```
Template Compiler Error (TemplateCompiler) in dummy/templates/application.hbs

Cannot read property 'start' of null
```

The error is gone after disabling `ember-ast-hot-load`. I upgraded this project to Ember 3.25 and got the same error running `ember serve` with the following log:

<details>
<summary>Stack Trace and Error Report</summary>

```
=================================================================================

ENV Summary:

  TIME: Tue Mar 30 2021 16:20:45 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - /Users/nate/.nvm/versions/node/v14.15.4/bin/node
  - /Users/nate/.nvm/versions/node/v14.15.4/bin/ember
  - test
  EXEC_PATH: /Users/nate/.nvm/versions/node/v14.15.4/bin/node
  TMPDIR: /var/folders/9l/vmkxx6gs34b7tzz97z4msclm0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/nate/.nvm/versions/node/v14.15.4/bin
  - /Users/nate/Library/Android/SDK/platform-tools
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/MacGPG2/bin
  - /Library/Apple/usr/bin
  PLATFORM: darwin x64
  FREEMEM: 37510127616
  TOTALMEM: 77309411328
  UPTIME: 22179
  LOADAVG: 3.8935546875,2.28955078125,3.060546875
  CPUS:
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.16.1
  - brotli: 1.0.9
  - cldr: 37.0
  - icu: 67.1
  - llhttp: 2.1.3
  - modules: 83
  - napi: 7
  - nghttp2: 1.41.0
  - node: 14.15.4
  - openssl: 1.1.1i
  - tz: 2020a
  - unicode: 13.0
  - uv: 1.40.0
  - v8: 8.4.371.19-node.17
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot read property 'start' of null
    at Source.spanFor (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:9071:26)
    at BlockContext.loc (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14161:26)
    at StatementNormalizer.BlockStatement (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14484:31)
    at StatementNormalizer.normalize (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14402:23)
    at /Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14572:27
    at Array.map (<anonymous>)
    at ElementNormalizer.ElementNode (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14571:41)
    at StatementNormalizer.normalize (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14405:52)
    at /Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14572:27
    at Array.map (<anonymous>)
  - code: [undefined]
  - codeFrame: Cannot read property 'start' of null
  - errorMessage: dummy/templates/application.hbs: Cannot read property 'start' of null
        in /var/folders/9l/vmkxx6gs34b7tzz97z4msclm0000gn/T/broccoli-34381bt02hXuf24T7/out-134-colocated_template_processor
        at TemplateCompiler
  - errorType: Template Compiler Error
  - location:
    - column: [undefined]
    - file: dummy/templates/application.hbs
    - line: [undefined]
    - treeDir: /var/folders/9l/vmkxx6gs34b7tzz97z4msclm0000gn/T/broccoli-34381bt02hXuf24T7/out-134-colocated_template_processor
  - message: dummy/templates/application.hbs: Cannot read property 'start' of null
        in /var/folders/9l/vmkxx6gs34b7tzz97z4msclm0000gn/T/broccoli-34381bt02hXuf24T7/out-134-colocated_template_processor
        at TemplateCompiler
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: TemplateCompiler
  - originalErrorMessage: Cannot read property 'start' of null
  - stack: TypeError: Cannot read property 'start' of null
    at Source.spanFor (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:9071:26)
    at BlockContext.loc (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14161:26)
    at StatementNormalizer.BlockStatement (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14484:31)
    at StatementNormalizer.normalize (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14402:23)
    at /Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14572:27
    at Array.map (<anonymous>)
    at ElementNormalizer.ElementNode (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14571:41)
    at StatementNormalizer.normalize (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14405:52)
    at /Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14572:27
    at Array.map (<anonymous>)

=================================================================================
```
</details>

See https://github.com/emberjs/ember.js/issues/19482 along with this possibly [helpful comment](https://github.com/emberjs/ember.js/issues/19482#issuecomment-808461772):
>So it's hard to tell for sure, but the biggest reason we've seen issues like this is actually because of custom Handlebars template transforms which were not using the builder API. These transforms would leave out crucial node information, like `loc` info, which resulted in malformed nodes. The Handlebars AST and transforms are not something that we consider public API, so this failure would be expected if that was the case.
>
>Are there any addons you're using that could be doing template preprocessing? If you're unsure, I can try to help figure out a way to give you list of all transforms that are running in the template compiler and we can start there.

**Comment by lifeart** [comment]
Hi @nwhittaker, thank you for report!
Try `2.0.0`

**Comment by nwhittaker** [comment]
Thanks for quick work @lifeart, much appreciated.

I'm running into a new, similar error w/ modifiers now. I'll put together a test case and log a separate issue for that.
