### ISSUE TITLE
Modifier causes Template Compiler error in Ember 3.25

### ISSUE THREAD

**Issue by nwhittaker** [lifeart/ember-ast-hot-load#562]
After upgrading a project with **modifiers** to Ember 3.25, the following error appears when running `ember serve`:

```
Template Compiler Error (TemplateCompiler) in dummy/templates/application.hbs

Cannot read property 'type' of undefined
```

The error is gone after disabling `ember-ast-hot-load`. I added a failing test case to a fork of this project ([see comparison](https://github.com/lifeart/ember-ast-hot-load/compare/master...nwhittaker:master)) and got the same error running `ember serve` with the following log:

<details>
<summary>Stack Trace and Error Report</summary>

```
=================================================================================

ENV Summary:

  TIME: Fri Apr 02 2021 12:32:20 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - /Users/nate/.nvm/versions/node/v14.15.4/bin/node
  - /Users/nate/.nvm/versions/node/v14.15.4/bin/ember
  - t
  EXEC_PATH: /Users/nate/.nvm/versions/node/v14.15.4/bin/node
  TMPDIR: /var/folders/9l/vmkxx6gs34b7tzz97z4msclm0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/nate/.nvm/versions/node/v14.15.4/bin
  - /Users/nate/Library/Android/SDK/platform-tools
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/MacGPG2/bin
  - /Library/Apple/usr/bin
  PLATFORM: darwin x64
  FREEMEM: 7032606720
  TOTALMEM: 77309411328
  UPTIME: 267681
  LOADAVG: 4.80615234375,2.3642578125,2.68798828125
  CPUS:
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.16.1
  - brotli: 1.0.9
  - cldr: 37.0
  - icu: 67.1
  - llhttp: 2.1.3
  - modules: 83
  - napi: 7
  - nghttp2: 1.41.0
  - node: 14.15.4
  - openssl: 1.1.1i
  - tz: 2020a
  - unicode: 13.0
  - uv: 1.40.0
  - v8: 8.4.371.19-node.17
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot read property 'type' of undefined
    at BlockContext.isFreeVar (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14194:25)
    at BlockContext.isFreeVar (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14200:21)
    at BlockContext.resolutionFor (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14171:16)
    at ElementNormalizer.modifier (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14609:33)
    at /Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14566:24
    at Array.map (<anonymous>)
    at ElementNormalizer.ElementNode (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14565:41)
    at StatementNormalizer.normalize (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14405:52)
    at /Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14506:27
    at Array.map (<anonymous>)
  - code: [undefined]
  - codeFrame: Cannot read property 'type' of undefined
  - errorMessage: dummy/templates/application.hbs: Cannot read property 'type' of undefined
        in /var/folders/9l/vmkxx6gs34b7tzz97z4msclm0000gn/T/broccoli-90878UA15IWGWRJfK/out-141-colocated_template_processor
        at TemplateCompiler
  - errorType: Template Compiler Error
  - location:
    - column: [undefined]
    - file: dummy/templates/application.hbs
    - line: [undefined]
    - treeDir: /var/folders/9l/vmkxx6gs34b7tzz97z4msclm0000gn/T/broccoli-90878UA15IWGWRJfK/out-141-colocated_template_processor
  - message: dummy/templates/application.hbs: Cannot read property 'type' of undefined
        in /var/folders/9l/vmkxx6gs34b7tzz97z4msclm0000gn/T/broccoli-90878UA15IWGWRJfK/out-141-colocated_template_processor
        at TemplateCompiler
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: TemplateCompiler
  - originalErrorMessage: Cannot read property 'type' of undefined
  - stack: TypeError: Cannot read property 'type' of undefined
    at BlockContext.isFreeVar (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14194:25)
    at BlockContext.isFreeVar (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14200:21)
    at BlockContext.resolutionFor (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14171:16)
    at ElementNormalizer.modifier (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14609:33)
    at /Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14566:24
    at Array.map (<anonymous>)
    at ElementNormalizer.ElementNode (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14565:41)
    at StatementNormalizer.normalize (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14405:52)
    at /Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/ember-template-compiler.js:14506:27
    at Array.map (<anonymous>)

=================================================================================
```
</details>

Likely a similar issue to https://github.com/lifeart/ember-ast-hot-load/issues/558.

**Comment by lifeart** [comment]
Hi @nwhittaker! Thank you for report! `ember-ast-hot-load@2.0.1` landed
