### ISSUE TITLE
HTML block content causing Template Compiler Error in Ember 3.25

### ISSUE THREAD

**Issue by nwhittaker** [lifeart/ember-ast-hot-load#564]
Follow-on issue to #562. Have templates with a structure like `<ComponentName><div>...</div></ComponentName>` and seeing the following error when running `ember serve`:

```
Template Compiler Error (TemplateCompiler) in dummy/templates/application.hbs

loc$$1.sliceStartChars is not a function
```

The error is gone after disabling `ember-ast-hot-load`. I added a failing test case to a fork of this project (see https://github.com/nwhittaker/ember-ast-hot-load/commit/a3917e03e1db93eea6d13c0581b7085419c8f29b) and got the same error running ember serve with the following log:

<details>
<summary>Stack Trace and Error Report</summary>

```
=================================================================================

ENV Summary:

  TIME: Sun Apr 04 2021 21:58:02 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - /Users/nate/.nvm/versions/node/v14.15.4/bin/node
  - /Users/nate/.nvm/versions/node/v14.15.4/bin/ember
  - s
  EXEC_PATH: /Users/nate/.nvm/versions/node/v14.15.4/bin/node
  TMPDIR: /var/folders/9l/vmkxx6gs34b7tzz97z4msclm0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/nate/.nvm/versions/node/v14.15.4/bin
  - /Users/nate/Library/Android/SDK/platform-tools
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/MacGPG2/bin
  - /Library/Apple/usr/bin
  PLATFORM: darwin x64
  FREEMEM: 4089454592
  TOTALMEM: 77309411328
  UPTIME: 474431
  LOADAVG: 2.1552734375,2.0361328125,2.291015625
  CPUS:
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz - 3800
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.16.1
  - brotli: 1.0.9
  - cldr: 37.0
  - icu: 67.1
  - llhttp: 2.1.3
  - modules: 83
  - napi: 7
  - nghttp2: 1.41.0
  - node: 14.15.4
  - openssl: 1.1.1i
  - tz: 2020a
  - unicode: 13.0
  - uv: 1.40.0
  - v8: 8.4.371.19-node.17
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: loc$$1.sliceStartChars is not a function
    at ElementNormalizer.classifyTag (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6996:1)
    at ElementNormalizer.ElementNode (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6806:1)
    at StatementNormalizer.normalize (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6657:1)
    at /Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6824:1
    at Array.map (<anonymous>)
    at ElementNormalizer.ElementNode (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6823:1)
    at StatementNormalizer.normalize (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6657:1)
    at /Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6758:1
    at Array.map (<anonymous>)
    at StatementNormalizer.Block (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6757:1)
  - code: [undefined]
  - codeFrame: loc$$1.sliceStartChars is not a function
  - errorMessage: dummy/templates/application.hbs: loc$$1.sliceStartChars is not a function
        in /var/folders/9l/vmkxx6gs34b7tzz97z4msclm0000gn/T/broccoli-5221891DjLC1j1jdp/out-141-colocated_template_processor
        at TemplateCompiler
  - errorType: Template Compiler Error
  - location:
    - column: [undefined]
    - file: dummy/templates/application.hbs
    - line: [undefined]
    - treeDir: /var/folders/9l/vmkxx6gs34b7tzz97z4msclm0000gn/T/broccoli-5221891DjLC1j1jdp/out-141-colocated_template_processor
  - message: dummy/templates/application.hbs: loc$$1.sliceStartChars is not a function
        in /var/folders/9l/vmkxx6gs34b7tzz97z4msclm0000gn/T/broccoli-5221891DjLC1j1jdp/out-141-colocated_template_processor
        at TemplateCompiler
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: TemplateCompiler
  - originalErrorMessage: loc$$1.sliceStartChars is not a function
  - stack: TypeError: loc$$1.sliceStartChars is not a function
    at ElementNormalizer.classifyTag (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6996:1)
    at ElementNormalizer.ElementNode (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6806:1)
    at StatementNormalizer.normalize (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6657:1)
    at /Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6824:1
    at Array.map (<anonymous>)
    at ElementNormalizer.ElementNode (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6823:1)
    at StatementNormalizer.normalize (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6657:1)
    at /Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6758:1
    at Array.map (<anonymous>)
    at StatementNormalizer.Block (/Users/nate/Sites/ember-ast-hot-load/node_modules/ember-source/dist/@glimmer/syntax.js:6757:1)

=================================================================================
```
</details>

Possibly some relevant info in https://github.com/emberjs/ember.js/issues/19432.

**Comment by lifeart** [comment]
Hi @nwhittaker! Thank you for report! `ember-ast-hot-load@2.0.2` landed
