### ISSUE TITLE
Unknown Transformation: 'fastboot-safe'

### ISSUE THREAD

**Issue by jbryson3** [lifeart/ember-ast-hot-load#68]
I'm tried installing this addon on an ember@2.13.3 app (no fastboot) and ran into the following error on `ember s`.

```
Error: while importing node_modules/ember-source/dist/ember-template-compiler.js: unknown transformation `fastboot-safe`
    at options.using.forEach.entry (/Users/jbryson3/code/arbiter/node_modules/ember-cli/lib/broccoli/ember-app.js:1563:19)
    at Array.forEach (<anonymous>)
    at EmberApp._import (/Users/jbryson3/code/arbiter/node_modules/ember-cli/lib/broccoli/ember-app.js:1558:23)
    at EmberApp.import (/Users/jbryson3/code/arbiter/node_modules/ember-cli/lib/broccoli/ember-app.js:1533:10)
    at Class.included (/Users/jbryson3/code/arbiter/node_modules/ember-ast-hot-load/index.js:198:17)
    at Class.superWrapper [as included] (/Users/jbryson3/code/arbiter/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at EmberApp.<anonymous> (/Users/jbryson3/code/arbiter/node_modules/ember-cli/lib/broccoli/ember-app.js:517:17)
    at Array.filter (<anonymous>)
    at EmberApp._notifyAddonIncluded (/Users/jbryson3/code/arbiter/node_modules/ember-cli/lib/broccoli/ember-app.js:512:47)
    at new EmberApp (/Users/jbryson3/code/arbiter/node_modules/ember-cli/lib/broccoli/ember-app.js:142:10)
```

**Comment by lifeart** [comment]
Hi @jbryson3! Thank you for report!
 Could you plz provide ember-cli version? Issue may be related to https://github.com/ember-cli/ember-cli/pull/7245 (in older ember-cli versions `importTransforms` not implemented) Also, it will be great, if you can create minimal reproduction repo. Thanks!

**Comment by lifeart** [comment]
`ember-cli@v2.15.1` should support `importTransforms` from addons

**Comment by jbryson3** [comment]
I'm on an older version than supported `ember-cli: 2.13.2` - thanks for the quick reply!

**Comment by lifeart** [comment]
@jbryson3 you can try https://github.com/adopted-ember-addons/ember-cli-hot-loader 
or just replace
https://github.com/lifeart/ember-ast-hot-load/blob/master/index.js#L198
to 
`app.import(npmPath);`
